spring.application.name=Test1
server.port=8886
spring.datasource.url=jdbc:postgresql://localhost:5432/Test1
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect